inherit_from: .rubocop_todo.yml

require: rubocop-rails

AllCops:
  Exclude:
    - "db/schema.rb"
    - "vendor/**/*"
    - "spec/support/gravity_helper.rb"
    - "spec/support/taxjar_helper.rb"
    - "db/migrate/**"

Metrics/ParameterLists:
  Max: 11

Metrics/ClassLength:
  Max: 1000000

Metrics/AbcSize:
  Max: 61
  Exclude:
    - "db/migrate/*"

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "app/admin/**/*"

Metrics/MethodLength:
  Max: 43
  Exclude:
    - "db/migrate/*"

Metrics/ModuleLength:
  Max: 137
  Exclude:
    - "spec/**/*"

Style/FormatStringToken:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: false

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
