version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5
  hokusai: artsy/hokusai@0.7.3

not_staging_or_release: &not_staging_or_release
  filters:
    branches:
      ignore:
        - staging
        - release

only_master: &only_master
  context: hokusai
  filters:
    branches:
      only: master

only_release: &only_release
  context: hokusai
  filters:
    branches:
      only: release

workflows:
  default:
    jobs:
      # pre-staging
      - hokusai/test:
          name: test
          <<: *not_staging_or_release
          post-steps:
            - run:
                name: Copy coverage artifacts
                command: mkdir -p ./coverage && docker cp hokusai_exchange_1:/app/coverage ./
                when: on_success
            - codecov/upload:
                file: ./coverage/.resultset.json
                when: on_success

      # staging
      - hokusai/push:
          name: push-staging-image
          <<: *only_master
          requires:
            - test

      - hokusai/deploy-staging:
          <<: *only_master
          project-name: exchange
          requires:
            - push-staging-image

      # release
      - hokusai/deploy-production:
          <<: *only_release
