---
version: "2"
services:
  exchange:
{% include 'templates/docker-compose-service.yml.j2' %}
    ports:
      - 8080:8080
    environment:
      - RAILS_ENV=test
      - DATABASE_HOST=exchange-db
      - DATABASE_USER=postgres
      - REDIS_URL=redis://exchange-redis
      - CI_PULL_REQUEST=$CI_PULL_REQUEST
      - CIRCLE_PULL_REQUEST=$CIRCLE_PULL_REQUEST
      - CIRCLE_BUILD_NUM=$CIRCLE_BUILD_NUM
      - DANGER_GITHUB_API_TOKEN=$DANGER_GITHUB_API_TOKEN
      - CI=$CI
    command: ./hokusai/ci.sh
    depends_on:
      - exchange-db
      - exchange-redis
    volumes:
      - "../.git:/app/.git:ro"
  exchange-db:
    image: postgres:12.5-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  exchange-redis:
    image: redis:3.2-alpine
